// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS_lXVNhrUS-E6kMDgNVROeHLvCTfHYhU',
    appId: '1:411198408519:web:d982a3b995a2297132ae62',
    messagingSenderId: '411198408519',
    projectId: 'gymtrackerjuparopi-f0027',
    authDomain: 'gymtrackerjuparopi-f0027.firebaseapp.com',
    storageBucket: 'gymtrackerjuparopi-f0027.appspot.com',
    measurementId: 'G-X9FZQZL942',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi8cOMGWIh5s4wGDbZ2KcZTpX2OCn9veM',
    appId: '1:411198408519:android:3869c16113450f5132ae62',
    messagingSenderId: '411198408519',
    projectId: 'gymtrackerjuparopi-f0027',
    storageBucket: 'gymtrackerjuparopi-f0027.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYeTw7mA4laSza91IYgY_48hxOAkmSnv8',
    appId: '1:411198408519:ios:55efc3356c8a888132ae62',
    messagingSenderId: '411198408519',
    projectId: 'gymtrackerjuparopi-f0027',
    storageBucket: 'gymtrackerjuparopi-f0027.appspot.com',
    iosClientId: '411198408519-63vhqc588j3qdodppq9ie4knemq21qae.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYeTw7mA4laSza91IYgY_48hxOAkmSnv8',
    appId: '1:411198408519:ios:55efc3356c8a888132ae62',
    messagingSenderId: '411198408519',
    projectId: 'gymtrackerjuparopi-f0027',
    storageBucket: 'gymtrackerjuparopi-f0027.appspot.com',
    iosClientId: '411198408519-63vhqc588j3qdodppq9ie4knemq21qae.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymAppFlutter',
  );
}
